name: Update Server Stats

on:
  schedule:
    - cron: "0 0 * * *"      # every day at midnight UTC
  workflow_dispatch:         # manual trigger

jobs:
  build-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # so we can push back

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run stats script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py

      - name: Commit updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.csv chart.png || true
          git diff --quiet && echo "No changes to commit." || (
            git commit -m "📊 Update server stats $(date -u +'%Y-%m-%d')"
            git push
          )
